exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS'
exports.LOGIN_FAILURE = 'LOGIN_FAILURE'

exports.LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
exports.LOGOUT_FAILURE = 'LOGOUT_FAILURE'

exports.VIDEO_UPLOAD_STARTED = 'VIDEO_UPLOAD_STARTED'
exports.VIDEO_UPLOAD_MADE_PROGRESS = 'VIDEO_UPLOAD_MADE_PROGRESS'
exports.VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS'
exports.VIDEO_UPLOAD_FAILURE = 'VIDEO_UPLOAD_FAILURE'

exports.FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST'
exports.FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS'
exports.FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE'

exports.OBJECT_DETECTION_REQUEST = 'OBJECT_DETECTION_REQUEST'
exports.OBJECT_DETECTION_STARTED = 'OBJECT_DETECTION_STARTED'
exports.OBJECT_DETECTION_MADE_PROGRESS = 'OBJECT_DETECTION_MADE_PROGRESS'
exports.OBJECT_DETECTION_SUCCESS = 'OBJECT_DETECTION_SUCCESS'
exports.OBJECT_DETECTION_FAILURE = 'OBJECT_DETECTION_FAILURE'

exports.FETCH_VIDEO_REQUEST = 'FETCH_VIDEO_REQUEST'
exports.FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS'
exports.FETCH_VIDEO_FAILURE = 'FETCH_VIDEO_FAILURE'