exports.LOGIN_REQUEST = 'LOGIN_REQUEST'
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS'
exports.LOGIN_FAILURE = 'LOGIN_FAILURE'

exports.VIDEO_UPLOAD_STARTED = 'VIDEO_UPLOAD_STARTED'
exports.VIDEO_UPLOAD_MADE_PROGRESS = 'VIDEO_UPLOAD_MADE_PROGRESS'
exports.VIDEO_UPLOAD_SUCCESS = 'VIDEO_UPLOAD_SUCCESS'
exports.VIDEO_UPLOAD_FAILURE = 'VIDEO_UPLOAD_FAILURE'

exports.FETCH_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST'
exports.FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS'
exports.FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE'

exports.OBJECT_DETECTION_REQUEST = 'OBJECT_DETECTION_REQUEST'
exports.OBJECT_DETECTION_STARTED = 'OBJECT_DETECTION_STARTED'
exports.OBJECT_DETCTION_MADE_PROGRESS = 'OBJECT_DETCTION_MADE_PROGRESS'
exports.OBJECT_DETCTION_SUCCESS = 'OBJECT_DETCTION_SUCCESS'
exports.OBJECT_DETCTION_FAILURE = 'OBJECT_DETCTION_FAILURE'